# Generated by Django 6.0.5 on 2026-10-03 00:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flamingo", "0001_flamingokonto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="flamingoaccount",
            name="autoreply_enabled",
            field=models.BooleanField(default=False, verbose_name="Autosvar till den som frågar"),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="autoreply_text",
            field=models.TextField(
                default="Hej! Tack för din förfrågan. Vi har tagit emot den och hör av oss. Brådskar det går det bra att ringa oss.",
                verbose_name="Autosvarets text",
            ),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="google_ads_customer_id",
            field=models.CharField(
                blank=True,
                help_text="Tio siffror, till exempel 123-456-7890.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{3}-\\d{3}-\\d{4}$",
                        "Skriv kontots id som tio siffror, till exempel 123-456-7890.",
                    )
                ],
                verbose_name="Google Ads-kontots id",
            ),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="google_note",
            field=models.CharField(blank=True, max_length=300, verbose_name="Notering om Google"),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="google_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Inte påbörjat"),
                    ("requested_new", "Vill ha ett nytt konto"),
                    ("id_given", "Konto-id angivet"),
                    ("linked", "Kopplat under ADX"),
                    ("billing_ok", "Kopplat och betalning klar"),
                ],
                default="not_started",
                max_length=20,
                verbose_name="Google Ads",
            ),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="notify_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Mobil för sms om nya förfrågningar"
            ),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="notify_sms",
            field=models.BooleanField(
                default=False, verbose_name="Sms till mig om nya förfrågningar"
            ),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="scan_error",
            field=models.CharField(blank=True, max_length=300, verbose_name="Fel vid hämtningen"),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="scan_status",
            field=models.CharField(
                choices=[
                    ("none", "Inte hämtad"),
                    ("running", "Hämtas"),
                    ("done", "Hämtad"),
                    ("failed", "Misslyckades"),
                ],
                default="none",
                max_length=10,
                verbose_name="Hemsidan",
            ),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="scanned_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Hämtad"),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="website_url",
            field=models.URLField(blank=True, verbose_name="Hemsida"),
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Namn")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Utkast"),
                            ("in_review", "Hos ADX"),
                            ("needs_customer", "Väntar på dig"),
                            ("live", "Live"),
                            ("paused", "Pausad"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        help_text="Till exempel Nacka + 15 km.",
                        max_length=200,
                        verbose_name="Område",
                    ),
                ),
                (
                    "radius_km",
                    models.PositiveSmallIntegerField(default=15, verbose_name="Radie (km)"),
                ),
                (
                    "daily_budget_kr",
                    models.PositiveIntegerField(default=150, verbose_name="Budget per dag (kr)"),
                ),
                ("headlines", models.JSONField(blank=True, default=list, verbose_name="Rubriker")),
                (
                    "descriptions",
                    models.JSONField(blank=True, default=list, verbose_name="Beskrivningar"),
                ),
                ("keywords", models.JSONField(blank=True, default=list, verbose_name="Sökord")),
                (
                    "negatives",
                    models.JSONField(blank=True, default=list, verbose_name="Negativa sökord"),
                ),
                ("page", models.JSONField(blank=True, default=dict, verbose_name="Landningssidan")),
                (
                    "page_slug",
                    models.SlugField(max_length=80, unique=True, verbose_name="Sidans adress"),
                ),
                (
                    "google_campaign_id",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Kampanjens id hos Google"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Godkänd av kunden"),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Publicerad"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="flamingo.flamingoaccount",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kampanj",
                "verbose_name_plural": "Kampanjer",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("form", "Formulär"), ("call", "Samtal"), ("manual", "Manuell")],
                        default="form",
                        max_length=10,
                        verbose_name="Källa",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=120, verbose_name="Namn")),
                ("phone", models.CharField(blank=True, max_length=40, verbose_name="Telefon")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="E-post")),
                ("message", models.TextField(blank=True, verbose_name="Meddelande")),
                ("answers", models.JSONField(blank=True, default=dict, verbose_name="Svar")),
                (
                    "gclid",
                    models.CharField(blank=True, max_length=200, verbose_name="Googles klick-id"),
                ),
                ("utm", models.JSONField(blank=True, default=dict, verbose_name="UTM")),
                ("keyword", models.CharField(blank=True, max_length=200, verbose_name="Sökord")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Ny"),
                            ("contacted", "Kontaktad"),
                            ("quote", "Offert skickad"),
                            ("won", "Vunnen"),
                            ("lost", "Förlorad"),
                            ("junk", "Skräp"),
                        ],
                        default="new",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "value_kr",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Affärens värde (kr)"
                    ),
                ),
                ("won_at", models.DateTimeField(blank=True, null=True, verbose_name="Vunnen")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Kom in"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="flamingo.flamingoaccount",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="flamingo.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Förfrågan",
                "verbose_name_plural": "Förfrågningar",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ConversionUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value_kr", models.PositiveIntegerField(verbose_name="Värde (kr)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "I kö"),
                            ("exported", "Exporterad"),
                            ("sent", "Skickad"),
                            ("failed", "Misslyckades"),
                        ],
                        default="queued",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "exported_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Exporterad"),
                ),
                ("response", models.JSONField(blank=True, default=dict, verbose_name="Svar")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversion",
                        to="flamingo.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konvertering till Google",
                "verbose_name_plural": "Konverteringar till Google",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Tjänst")),
                (
                    "sales_mode",
                    models.CharField(
                        choices=[
                            ("call", "Ringer direkt"),
                            ("quote", "Vill ha offert"),
                            ("book", "Vill boka tid"),
                        ],
                        default="quote",
                        max_length=10,
                        verbose_name="Hur köper kunderna den?",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordning")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="flamingo.flamingoaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tjänst",
                "verbose_name_plural": "Tjänster",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="flamingo.service",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns",
                to="flamingo.service",
                verbose_name="Tjänst",
            ),
        ),
        migrations.CreateModel(
            name="SmsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("owner_notice", "Till dig om en ny förfrågan"),
                            ("autoreply", "Autosvar"),
                        ],
                        max_length=20,
                        verbose_name="Sort",
                    ),
                ),
                ("to", models.CharField(blank=True, max_length=20, verbose_name="Till")),
                ("body", models.TextField(verbose_name="Text")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Skickat"),
                            ("failed", "Misslyckades"),
                            ("not_configured", "Inte skickat: sms är inte inkopplat"),
                            ("disabled", "Inte skickat: avstängt i inställningarna"),
                        ],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "provider_id",
                    models.CharField(blank=True, max_length=64, verbose_name="Id hos 46elks"),
                ),
                ("error", models.CharField(blank=True, max_length=300, verbose_name="Fel")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_log",
                        to="flamingo.flamingoaccount",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_log",
                        to="flamingo.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sms",
                "verbose_name_plural": "Sms",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.SlugField(max_length=64, verbose_name="Nyckel")),
                ("label", models.CharField(max_length=120, verbose_name="Uppgift")),
                ("value", models.TextField(blank=True, verbose_name="Värde")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("site", "Hemsidan"),
                            ("google", "Google"),
                            ("customer", "Du"),
                            ("adx", "ADX"),
                        ],
                        default="customer",
                        max_length=10,
                        verbose_name="Källa",
                    ),
                ),
                ("confirmed", models.BooleanField(default=False, verbose_name="Bekräftad")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordning")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="flamingo.flamingoaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uppgift",
                "verbose_name_plural": "Uppgifter",
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "key"), name="flamingo_fact_unique_key"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("round", models.PositiveSmallIntegerField(verbose_name="Runda")),
                (
                    "submitted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Inskickad"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("pending", "Väntar på ADX"), ("done", "Granskad")],
                        default="pending",
                        max_length=10,
                        verbose_name="Läge",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Granskad"),
                ),
                (
                    "snapshot",
                    models.JSONField(blank=True, default=dict, verbose_name="Inskickat innehåll"),
                ),
                ("changes", models.JSONField(blank=True, default=list, verbose_name="Ändringar")),
                ("note", models.TextField(blank=True, verbose_name="Meddelande till kunden")),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="flamingo.campaign",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Granskare",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Granskning",
                "verbose_name_plural": "Granskningar",
                "ordering": ["-round"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "round"), name="flamingo_review_round"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["account", "status", "-created_at"], name="flamingo_lead_status"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(fields=["account", "status"], name="flamingo_campaign_status"),
        ),
    ]
