# Generated by Django 6.0.5 on 2026-10-03 02:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flamingo", "0002_verktyget"),
    ]

    operations = [
        migrations.AddField(
            model_name="flamingoaccount",
            name="ai_count",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="AI-förslag den dagen"),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="ai_day",
            field=models.DateField(blank=True, null=True, verbose_name="Dag för AI-förslagen"),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="scan_count",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Läsningar den dagen"),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="scan_day",
            field=models.DateField(blank=True, null=True, verbose_name="Dag för läsningarna"),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="scan_started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Senaste läsningen startade"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="ip_hash",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="IP (hash)"
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="daily_budget_kr",
            field=models.PositiveIntegerField(
                default=150,
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(5000),
                ],
                verbose_name="Budget per dag (kr)",
            ),
        ),
    ]
