# Generated by Django 6.0.5 on 2026-10-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flamingo", "0003_sparrar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smslog",
            name="status",
            field=models.CharField(
                choices=[
                    ("sending", "Skickas"),
                    ("sent", "Skickat"),
                    ("failed", "Misslyckades"),
                    ("not_configured", "Inte skickat: sms är inte inkopplat"),
                    ("disabled", "Inte skickat: avstängt i inställningarna"),
                ],
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
