# Generated by Django 6.0.5 on 2026-10-03 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

CLICK_ID_KEYS = ("gbraid", "wbraid")


def click_ids_out_of_utm(apps, schema_editor):
    """gbraid och wbraid låg i Lead.utm tills de fick egna fält."""
    Lead = apps.get_model("flamingo", "Lead")
    for lead in Lead.objects.filter(utm__has_any_keys=list(CLICK_ID_KEYS)).iterator():
        utm = dict(lead.utm or {})
        for key in CLICK_ID_KEYS:
            value = str(utm.pop(key, "") or "")[:200]
            if value and not getattr(lead, key):
                setattr(lead, key, value)
        lead.utm = utm
        lead.save(update_fields=["utm", *CLICK_ID_KEYS])


def click_ids_back_to_utm(apps, schema_editor):
    Lead = apps.get_model("flamingo", "Lead")
    leads = Lead.objects.exclude(gbraid="", wbraid="")
    for lead in leads.iterator():
        utm = dict(lead.utm or {})
        for key in CLICK_ID_KEYS:
            if getattr(lead, key):
                utm[key] = getattr(lead, key)
        lead.utm = utm
        lead.save(update_fields=["utm"])


class Migration(migrations.Migration):
    dependencies = [
        ("flamingo", "0004_sms_skickas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignDayStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="Dag")),
                ("cost_micros", models.BigIntegerField(default=0, verbose_name="Kostnad (mikros)")),
                ("impressions", models.PositiveIntegerField(default=0, verbose_name="Visningar")),
                ("clicks", models.PositiveIntegerField(default=0, verbose_name="Klick")),
                ("conversions", models.FloatField(default=0, verbose_name="Konverteringar")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dag i Googles rapport",
                "verbose_name_plural": "Dagar i Googles rapport",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="GoogleAdsConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "refresh_token_encrypted",
                    models.TextField(blank=True, editable=False, verbose_name="Nyckel (krypterad)"),
                ),
                (
                    "google_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Google-konto"),
                ),
                (
                    "connected_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Kopplad"),
                ),
                (
                    "last_ok_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Senaste lyckade anropet"
                    ),
                ),
                (
                    "last_error",
                    models.CharField(blank=True, max_length=300, verbose_name="Senaste felet"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Google Ads-koppling",
                "verbose_name_plural": "Google Ads-koppling",
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="google_error",
            field=models.CharField(blank=True, max_length=500, verbose_name="Fel från Google"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="google_publish_started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Publiceringen hos Google påbörjad"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="google_resources",
            field=models.JSONField(blank=True, default=dict, verbose_name="Resurser hos Google"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="google_synced_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Synkad med Google"),
        ),
        migrations.AddField(
            model_name="conversionupload",
            name="error",
            field=models.CharField(blank=True, max_length=300, verbose_name="Fel"),
        ),
        migrations.AddField(
            model_name="conversionupload",
            name="kind",
            field=models.CharField(
                choices=[
                    ("lead", "Förfrågan"),
                    ("call", "Klick på telefonnumret"),
                    ("deal", "Affär"),
                ],
                default="deal",
                max_length=10,
                verbose_name="Sort",
            ),
        ),
        migrations.AddField(
            model_name="conversionupload",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Skickad"),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="google_auto_tagging",
            field=models.BooleanField(blank=True, null=True, verbose_name="Automatisk taggning"),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="google_billing_status",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Betalningen hos Google"
            ),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="google_conversion_actions",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Konverteringar hos Google"
            ),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="google_link_requested_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Kopplingsinbjudan skickad"
            ),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="google_sync_error",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Fel vid läsningen från Google"
            ),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="google_synced_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Läst från Google"),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="is_demo",
            field=models.BooleanField(
                default=False,
                help_text="Demokonto: inga anrop till Google, inga sms, sidorna bara för byrån.",
                verbose_name="Demokonto",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="ad_consent",
            field=models.CharField(
                blank=True,
                choices=[("", "Inte tillfrågad"), ("granted", "Ja"), ("denied", "Nej")],
                default="",
                max_length=10,
                verbose_name="Samtycke till annonsmätning",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="gbraid",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Googles klick-id (gbraid)"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="wbraid",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Googles klick-id (wbraid)"
            ),
        ),
        migrations.AlterField(
            model_name="conversionupload",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversions",
                to="flamingo.lead",
            ),
        ),
        migrations.AlterField(
            model_name="conversionupload",
            name="value_kr",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Värde (kr)"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("form", "Formulär"),
                    ("call", "Samtal"),
                    ("manual", "Manuell"),
                    ("call_click", "Klick på telefonnumret"),
                ],
                default="form",
                max_length=10,
                verbose_name="Källa",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversionupload",
            constraint=models.UniqueConstraint(
                fields=("lead", "kind"), name="flamingo_conversion_kind"
            ),
        ),
        migrations.AddField(
            model_name="campaigndaystats",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="day_stats",
                to="flamingo.campaign",
            ),
        ),
        migrations.AddField(
            model_name="googleadsconnection",
            name="connected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kopplad av",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaigndaystats",
            constraint=models.UniqueConstraint(
                fields=("campaign", "date"), name="flamingo_daystats_day"
            ),
        ),
        migrations.RunPython(click_ids_out_of_utm, click_ids_back_to_utm),
    ]
