# Generated by Django 6.0.5 on 2026-10-03 09:57

from django.db import migrations, models


def earlier_campaigns_were_reviewed(apps, schema_editor):
    """Före valet granskade ADX varje kampanj: de som skickats in (har en
    granskningsrunda, eller ligger hos ADX) räknas som att kunden bad om
    granskning, så att kön och historiken ser ut som förut."""
    Campaign = apps.get_model("flamingo", "Campaign")
    Campaign.objects.filter(models.Q(reviews__isnull=False) | models.Q(status="in_review")).update(
        review_requested=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ("flamingo", "0005_google_ads"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="review_requested",
            field=models.BooleanField(default=False, verbose_name="Kunden bad om granskning"),
        ),
        migrations.RunPython(earlier_campaigns_were_reviewed, migrations.RunPython.noop),
    ]
