# Generated by Django 6.0.5 on 2026-10-03 10:47

from django.db import migrations, models


def no_shared_google_ids(apps, schema_editor):
    """Två riktiga Flamingo-konton med samma Google Ads-id stoppar
    migreringen med kontonas nummer, i stället för databasens eget fel.
    Rätta id:t på kundkortet (eller i admin) och kör migreringen igen."""
    FlamingoAccount = apps.get_model("flamingo", "FlamingoAccount")
    seen, shared = {}, []
    rows = (
        FlamingoAccount.objects.filter(is_demo=False)
        .exclude(google_ads_customer_id="")
        .order_by("pk")
        .values_list("pk", "google_ads_customer_id")
    )
    for pk, google_id in rows:
        if google_id in seen:
            shared.append(f"{google_id}: konto {seen[google_id]} och {pk}")
        else:
            seen[google_id] = pk
    if shared:
        raise RuntimeError(
            "Flera Flamingo-konton har samma Google Ads-id. Rätta det innan migreringen: "
            + "; ".join(shared)
        )


class Migration(migrations.Migration):
    dependencies = [
        ("flamingo", "0006_kundens_granskning"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="agency_alert_subject",
            field=models.CharField(blank=True, max_length=200, verbose_name="Larmets ämne"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="agency_alerted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Byrån larmad"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="google_attempted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Senaste misslyckade publiceringen efter kunden"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="google_publish_sent",
            field=models.JSONField(blank=True, default=dict, verbose_name="Skickat till Google"),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="google_link_requested_for",
            field=models.CharField(blank=True, max_length=20, verbose_name="Förfrågan gällde id"),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="publish_count",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Publiceringsförsök den dagen"
            ),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="publish_day",
            field=models.DateField(blank=True, null=True, verbose_name="Dag för publiceringarna"),
        ),
        migrations.AddField(
            model_name="googleadsconnection",
            name="conversion_upload_blocked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Uppladdningen av konverteringar stoppad"
            ),
        ),
        migrations.AddField(
            model_name="googleadsconnection",
            name="conversion_upload_error",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Varför uppladdningen stoppades"
            ),
        ),
        migrations.RunPython(no_shared_google_ids, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="flamingoaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("google_ads_customer_id", ""), _negated=True), ("is_demo", False)
                ),
                fields=("google_ads_customer_id",),
                name="flamingo_google_id_unique",
            ),
        ),
    ]
