# Generated by Django 6.0.5 on 2026-10-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flamingo", "0007_google_sakerhet"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversionupload",
            name="attempts",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Försök som inte gick fram"
            ),
        ),
        migrations.AddField(
            model_name="conversionupload",
            name="checked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Googles besked läst"),
        ),
        migrations.AddField(
            model_name="conversionupload",
            name="downloaded_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="I en nedladdad fil"),
        ),
        migrations.AddField(
            model_name="conversionupload",
            name="next_attempt_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Nästa försök"),
        ),
        migrations.AddField(
            model_name="conversionupload",
            name="request_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Sändningens id hos Google"
            ),
        ),
        migrations.AddField(
            model_name="googleadsconnection",
            name="conversion_upload_blocked_path",
            field=models.CharField(blank=True, max_length=20, verbose_name="Vägen som stoppades"),
        ),
        migrations.AddField(
            model_name="googleadsconnection",
            name="granted_scopes",
            field=models.TextField(blank=True, verbose_name="Behörigheter hos Google"),
        ),
        migrations.AddField(
            model_name="googleadsconnection",
            name="scopes_for",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=16,
                verbose_name="Behörigheterna gäller nyckeln",
            ),
        ),
    ]
