# Generated by Django 6.0.5 on 2026-10-03 17:03

from django.db import migrations, models


def mark_taken_back(apps, schema_editor):
    """Fram till nu kunde byrån bara skicka in genom att ta tillbaka en
    godkänd kampanj (kundvyn var skrivskyddad), så en runda inskickad av
    byrån var alltid en sådan."""
    Review = apps.get_model("flamingo", "Review")
    Review.objects.filter(submitted_by__is_staff=True).update(taken_back=True)


class Migration(migrations.Migration):
    dependencies = [
        ("flamingo", "0008_data_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="taken_back",
            field=models.BooleanField(default=False, verbose_name="ADX tog tillbaka kampanjen"),
        ),
        migrations.RunPython(mark_taken_back, migrations.RunPython.noop),
    ]
