# Generated by Django 6.0.5 on 2026-10-03 18:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.flamingo.models


class Migration(migrations.Migration):
    dependencies = [
        ("flamingo", "0009_tillbaka_till_granskning"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="flamingoaccount",
            name="google_maps_uri",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Profilen på Google Maps"
            ),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="google_place_id",
            field=models.CharField(blank=True, max_length=200, verbose_name="Googles Place ID"),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="google_place_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="Namnet på Google"),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="google_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=2,
                null=True,
                verbose_name="Betyg på Google",
            ),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="google_review_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Antal omdömen på Google"
            ),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="google_reviews",
            field=models.JSONField(blank=True, default=list, verbose_name="Omdömen från Google"),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="google_reviews_fetched_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Omdömena hämtade"),
        ),
        migrations.AddField(
            model_name="flamingoaccount",
            name="google_reviews_selected",
            field=models.JSONField(blank=True, default=list, verbose_name="Valda omdömen"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="page",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Landningssidan före sidbyggaren"
            ),
        ),
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Namn")),
                (
                    "design",
                    models.CharField(
                        choices=[("ren", "Ren")],
                        default="ren",
                        max_length=20,
                        verbose_name="Design",
                    ),
                ),
                (
                    "palette",
                    models.CharField(
                        choices=[
                            ("blue", "Blå"),
                            ("green", "Grön"),
                            ("red", "Röd"),
                            ("orange", "Orange"),
                            ("graphite", "Grafit"),
                            ("logo", "Från logotypen"),
                        ],
                        default="blue",
                        max_length=20,
                        verbose_name="Palett",
                    ),
                ),
                (
                    "logo_colors",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Färger från logotypen"
                    ),
                ),
                (
                    "draft",
                    models.JSONField(
                        blank=True,
                        default=apps.flamingo.models.empty_page_content,
                        verbose_name="Utkast",
                    ),
                ),
                (
                    "published",
                    models.JSONField(
                        blank=True,
                        default=apps.flamingo.models.empty_page_content,
                        verbose_name="Publicerad",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Publicerad"),
                ),
                ("rev", models.PositiveIntegerField(default=1, verbose_name="Version av utkastet")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landing_pages",
                        to="flamingo.flamingoaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Publicerad av",
                    ),
                ),
            ],
            options={
                "verbose_name": "Landningssida",
                "verbose_name_plural": "Landningssidor",
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="landing_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="campaigns",
                to="flamingo.landingpage",
                verbose_name="Landningssida",
            ),
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        height_field="height",
                        max_length=200,
                        upload_to=apps.flamingo.models.media_upload_path,
                        verbose_name="Bild",
                        width_field="width",
                    ),
                ),
                (
                    "thumb",
                    models.ImageField(
                        blank=True,
                        max_length=200,
                        upload_to=apps.flamingo.models.media_upload_path,
                        verbose_name="Miniatyr",
                    ),
                ),
                ("width", models.PositiveIntegerField(default=0, verbose_name="Bredd")),
                ("height", models.PositiveIntegerField(default=0, verbose_name="Höjd")),
                (
                    "alt",
                    models.CharField(blank=True, max_length=200, verbose_name="Alternativtext"),
                ),
                ("is_logo", models.BooleanField(default=False, verbose_name="Logotyp")),
                (
                    "source",
                    models.CharField(
                        choices=[("upload", "Uppladdad"), ("site", "Från hemsidan")],
                        default="upload",
                        max_length=10,
                        verbose_name="Källa",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, max_length=500, verbose_name="Adress på hemsidan"),
                ),
                (
                    "rights_confirmed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Rätten intygad"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="flamingo.flamingoaccount",
                    ),
                ),
                (
                    "rights_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Intygad av",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bild",
                "verbose_name_plural": "Bilder",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SiteImageCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_url", models.URLField(max_length=500, verbose_name="Adress på hemsidan")),
                (
                    "thumb",
                    models.ImageField(
                        blank=True,
                        max_length=200,
                        upload_to=apps.flamingo.models.media_upload_path,
                        verbose_name="Miniatyr",
                    ),
                ),
                ("width", models.PositiveIntegerField(blank=True, null=True, verbose_name="Bredd")),
                ("height", models.PositiveIntegerField(blank=True, null=True, verbose_name="Höjd")),
                (
                    "found_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Hittad"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_images",
                        to="flamingo.flamingoaccount",
                    ),
                ),
                (
                    "imported_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidates",
                        to="flamingo.mediaasset",
                        verbose_name="Hämtad som",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bild från hemsidan",
                "verbose_name_plural": "Bilder från hemsidan",
                "ordering": ["-found_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(fields=["account", "-created_at"], name="flamingo_media_account"),
        ),
        migrations.AddConstraint(
            model_name="siteimagecandidate",
            constraint=models.UniqueConstraint(
                fields=("account", "source_url"), name="flamingo_site_image_unique"
            ),
        ),
    ]
