# Generated by Django 6.0.5 on 2026-10-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flamingo", "0011_sidor_fran_kampanjerna"),
    ]

    operations = [
        migrations.AddField(
            model_name="flamingoaccount",
            name="daily_usage",
            field=models.JSONField(blank=True, default=dict, verbose_name="Dagens användning"),
        ),
        migrations.AddField(
            model_name="siteimagecandidate",
            name="alt",
            field=models.CharField(blank=True, max_length=200, verbose_name="Alt-text på hemsidan"),
        ),
        migrations.AddField(
            model_name="siteimagecandidate",
            name="likely_logo",
            field=models.BooleanField(default=False, verbose_name="Trolig logotyp"),
        ),
    ]
