# Generated by Django 6.0.5 on 2026-08-30 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.offers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Namn')),
                ('description', models.TextField(blank=True, verbose_name='Beskrivning')),
                ('default_price', models.PositiveIntegerField(default=0, verbose_name='Riktpris (kr exkl. moms)')),
                ('default_period', models.CharField(choices=[('one_time', 'Engång'), ('monthly', 'Per månad'), ('yearly', 'Per år')], default='one_time', max_length=10, verbose_name='Pristyp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkter',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.offers.models._generate_token, editable=False, max_length=48, unique=True)),
                ('customer_name', models.CharField(max_length=200, verbose_name='Kund')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Kundens e-post')),
                ('project_title', models.CharField(blank=True, max_length=200, verbose_name='Projekt')),
                ('intro', models.TextField(blank=True, help_text='Visas överst på kundens offertsida.', verbose_name='Hälsning')),
                ('status', models.CharField(choices=[('draft', 'Utkast'), ('sent', 'Skickad'), ('opened', 'Öppnad'), ('accepted', 'Accepterad'), ('declined', 'Förlorad')], default='draft', max_length=10)),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Giltig till')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('accepted_user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offert',
                'verbose_name_plural': 'Offerter',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Rad')),
                ('description', models.TextField(blank=True, verbose_name='Beskrivning')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Pris (kr exkl. moms)')),
                ('period', models.CharField(choices=[('one_time', 'Engång'), ('monthly', 'Per månad'), ('yearly', 'Per år')], default='one_time', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='offers.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='offers.quote')),
            ],
            options={
                'verbose_name': 'Offertrad',
                'verbose_name_plural': 'Offertrader',
                'ordering': ['order', 'id'],
            },
        ),
    ]
