# Generated by Django 6.0.5 on 2026-09-20 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0002_quoteline_is_optional_quoteline_is_selected"),
        ("projects", "0003_checklista_aktivitet"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotes",
                to="projects.project",
                verbose_name="Projekt",
            ),
        ),
        migrations.AddField(
            model_name="quoteline",
            name="issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quote_lines",
                to="projects.issue",
                verbose_name="Ärende",
            ),
        ),
    ]
