# Generated by Django 6.0.5 on 2026-09-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0003_offert_projekt"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="accept_billing_address",
            field=models.TextField(blank=True, verbose_name="Fakturaadress"),
        ),
        migrations.AddField(
            model_name="quote",
            name="accept_billing_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Faktura-e-post"),
        ),
        migrations.AddField(
            model_name="quote",
            name="accept_company",
            field=models.CharField(blank=True, max_length=200, verbose_name="Företag"),
        ),
        migrations.AddField(
            model_name="quote",
            name="accept_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-post"),
        ),
        migrations.AddField(
            model_name="quote",
            name="accept_first_name",
            field=models.CharField(blank=True, max_length=80, verbose_name="Förnamn"),
        ),
        migrations.AddField(
            model_name="quote",
            name="accept_last_name",
            field=models.CharField(blank=True, max_length=80, verbose_name="Efternamn"),
        ),
        migrations.AddField(
            model_name="quote",
            name="accept_message",
            field=models.TextField(blank=True, verbose_name="Meddelande"),
        ),
        migrations.AddField(
            model_name="quote",
            name="accept_org_number",
            field=models.CharField(blank=True, max_length=20, verbose_name="Organisationsnummer"),
        ),
        migrations.AddField(
            model_name="quote",
            name="accept_phone",
            field=models.CharField(blank=True, max_length=40, verbose_name="Telefon"),
        ),
        migrations.AddField(
            model_name="quote",
            name="accept_reference",
            field=models.CharField(blank=True, max_length=100, verbose_name="Er referens"),
        ),
    ]
