# Generated by Django 6.0.5 on 2026-09-20 14:21

import django.db.models.deletion
from django.db import migrations, models

import apps.offers.models
import apps.projects.models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0004_bestallarens_uppgifter"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=apps.projects.models.private_storage,
                        upload_to=apps.offers.models.quote_attachment_path,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("size", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="offers.quote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offertbilaga",
                "verbose_name_plural": "Offertbilagor",
                "ordering": ["created_at", "id"],
            },
        ),
    ]
