# Generated by Django 6.0.5 on 2026-09-20 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0005_offertbilagor"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="copied_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copies",
                to="offers.quote",
            ),
        ),
    ]
