# Generated by Django 6.0.5 on 2026-10-01 15:05

from django.db import migrations, models

WEBSITE_INCLUDES = """Design efter ert varumärke: Ett förslag ni godkänner innan vi bygger.
Fungerar på alla skärmar: Mobil, surfplatta och dator.
Innehåll och texter: För alla sidor, skrivna för era kunder och för sökmotorerna.
Synlig på Google: Sökordsanalys och teknisk optimering vid lansering.
Ni redigerar själva: Texter och bilder i en enkel panel.
Besöksstatistik: Utan tredjepartskakor, så att ni ser vad som fungerar."""

DEFAULT_TERMS = """Fakturering: 50 % vid start och 50 % vid lansering, 30 dagars betalningsvillkor.
Ni äger domänen, innehållet och bilderna."""


def seed(apps, schema_editor):
    # Startpunkt att redigera i /manage/produkter/. Befintliga offerter rörs
    # inte: en skickad eller accepterad offert får inga villkor i efterhand.
    OfferText = apps.get_model("offers", "OfferText")
    if not OfferText.objects.exists():
        OfferText.objects.create(
            kind="terms", name="Standardvillkor", text=DEFAULT_TERMS, is_default=True
        )
        OfferText.objects.create(kind="includes", name="Ny webbplats", text=WEBSITE_INCLUDES)


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0006_kopierad_fran"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("includes", "Det här ingår"), ("terms", "Villkor")],
                        max_length=10,
                        verbose_name="Typ",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Namn")),
                ("text", models.TextField(help_text="En rad per punkt.", verbose_name="Text")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Standard för nya offerter"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Offerttext",
                "verbose_name_plural": "Offerttexter",
                "ordering": ["kind", "order", "name"],
            },
        ),
        migrations.AddField(
            model_name="quote",
            name="includes",
            field=models.TextField(
                blank=True,
                help_text="En rad per punkt. 'Rubrik: förklaring' ger fet rubrik och förklaring under.",
                verbose_name="Det här ingår",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="terms",
            field=models.TextField(
                blank=True,
                help_text="En rad per villkor. Moms och giltighetstid skrivs automatiskt.",
                verbose_name="Villkor",
            ),
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
