# Generated by Django 6.0.5 on 2026-10-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0007_offerttexter_villkor"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="decline_message",
            field=models.TextField(blank=True, verbose_name="Kundens kommentar"),
        ),
        migrations.AddField(
            model_name="quote",
            name="decline_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("price", "Priset passar inte"),
                    ("other_supplier", "Vi har valt en annan leverantör"),
                    ("timing", "Inte aktuellt just nu"),
                    ("scope", "Förslaget passar inte våra behov"),
                    ("other", "Annat"),
                ],
                max_length=20,
                verbose_name="Skäl",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="declined_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
