# Generated by Django 6.0.5 on 2026-09-06 01:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=60, verbose_name="Rubrik")),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "wip_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Tomt = ingen gräns.",
                        null=True,
                        verbose_name="Max samtidiga",
                    ),
                ),
                (
                    "is_done",
                    models.BooleanField(
                        default=False,
                        help_text="Ärenden som flyttas hit räknas som klara.",
                        verbose_name="Avslutar ärendet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kolumn",
                "verbose_name_plural": "Kolumner",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Namn")),
                (
                    "org_number",
                    models.CharField(blank=True, max_length=20, verbose_name="Organisationsnummer"),
                ),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="E-post")),
                ("phone", models.CharField(blank=True, max_length=40, verbose_name="Telefon")),
                ("website", models.URLField(blank=True, verbose_name="Webbplats")),
                ("notes", models.TextField(blank=True, verbose_name="Anteckningar")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kund",
                "verbose_name_plural": "Kunder",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True, verbose_name="Namn")),
                ("color", models.CharField(default="#e8930c", max_length=7, verbose_name="Färg")),
            ],
            options={
                "verbose_name": "Etikett",
                "verbose_name_plural": "Etiketter",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number", models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ("title", models.CharField(max_length=200, verbose_name="Rubrik")),
                ("description", models.TextField(blank=True, verbose_name="Beskrivning")),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("task", "Uppgift"),
                            ("bug", "Fel"),
                            ("feature", "Ny funktion"),
                            ("support", "Support"),
                        ],
                        default="task",
                        max_length=10,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(10, "Låg"), (20, "Normal"), (30, "Hög"), (40, "Akut")],
                        default=20,
                        verbose_name="Prioritet",
                    ),
                ),
                (
                    "estimate_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Uppskattning (minuter)"
                    ),
                ),
                ("due_on", models.DateField(blank=True, null=True, verbose_name="Förfaller")),
                ("is_billable", models.BooleanField(default=True, verbose_name="Fakturerbart")),
                ("position", models.PositiveIntegerField(default=0)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_issues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ansvarig",
                    ),
                ),
                (
                    "column",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issues",
                        to="projects.column",
                        verbose_name="Kolumn",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issues",
                        to="projects.customer",
                        verbose_name="Kund",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "labels",
                    models.ManyToManyField(blank=True, related_name="issues", to="projects.label"),
                ),
            ],
            options={
                "verbose_name": "Ärende",
                "verbose_name_plural": "Ärenden",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("body", models.TextField(verbose_name="Kommentar")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="projects.issue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kommentar",
                "verbose_name_plural": "Kommentarer",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Namn")),
                ("key", models.CharField(max_length=10, unique=True, verbose_name="Nyckel")),
                ("description", models.TextField(blank=True, verbose_name="Beskrivning")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktivt"),
                            ("paused", "Pausat"),
                            ("done", "Avslutat"),
                            ("archived", "Arkiverat"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "hourly_rate",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Tomt = inte fakturerat per timme.",
                        null=True,
                        verbose_name="Timpris (kr)",
                    ),
                ),
                (
                    "budget_hours",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Budget (timmar)"
                    ),
                ),
                ("starts_on", models.DateField(blank=True, null=True, verbose_name="Start")),
                ("due_on", models.DateField(blank=True, null=True, verbose_name="Deadline")),
                ("next_issue_number", models.PositiveIntegerField(default=1, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="projects.customer",
                        verbose_name="Kund",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projekt",
                "verbose_name_plural": "Projekt",
                "ordering": ["status", "name"],
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issues",
                to="projects.project",
                verbose_name="Projekt",
            ),
        ),
        migrations.AddField(
            model_name="column",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="projects.project",
            ),
        ),
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("seconds", models.PositiveIntegerField(default=0)),
                ("note", models.CharField(blank=True, max_length=300, verbose_name="Anteckning")),
                ("is_billable", models.BooleanField(default=True, verbose_name="Fakturerbart")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="projects.issue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="time_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tidspost",
                "verbose_name_plural": "Tidsposter",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["project", "column", "position"], name="projects_is_project_f6691f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["customer", "closed_at"], name="projects_is_custome_8fe1b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["assignee", "closed_at"], name="projects_is_assigne_53adca_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="issue",
            constraint=models.UniqueConstraint(
                fields=("project", "number"), name="unique_issue_number_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="issue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("project__isnull", False), ("number__isnull", True), _connector="OR"
                ),
                name="issue_number_requires_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="column",
            constraint=models.UniqueConstraint(
                fields=("project", "title"), name="unique_column_title_per_project"
            ),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(fields=["user", "ended_at"], name="projects_ti_user_id_33a3f0_idx"),
        ),
        migrations.AddConstraint(
            model_name="timeentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at__isnull", True)),
                fields=("user",),
                name="one_running_timer_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="timeentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ended_at__isnull", True),
                    ("ended_at__gte", models.F("started_at")),
                    _connector="OR",
                ),
                name="time_entry_ends_after_start",
            ),
        ),
    ]
