# Generated by Django 6.0.5 on 2026-09-06 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.projects.models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_internal",
            field=models.BooleanField(default=False, verbose_name="Intern anteckning"),
        ),
        migrations.AddField(
            model_name="customer",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="customers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kontakter",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="created_in_portal",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="issue",
            name="visible_to_customer",
            field=models.BooleanField(default=False, verbose_name="Synlig för kund"),
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=apps.projects.models.private_storage,
                        upload_to=apps.projects.models.attachment_path,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("size", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="projects.issue",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bilaga",
                "verbose_name_plural": "Bilagor",
                "ordering": ["created_at"],
            },
        ),
    ]
