# Generated by Django 6.0.5 on 2026-09-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_inloggningskod"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="page_url",
            field=models.URLField(blank=True, verbose_name="Gäller sida"),
        ),
        migrations.AddField(
            model_name="issue",
            name="request_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("build", "Genomför det som beskrivs"),
                    ("advice", "Ge oss förslag och råd först"),
                    ("quote", "Vi vill ha en offert"),
                ],
                max_length=10,
                verbose_name="Vad kunden vill",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="urgency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "Ingen brådska"),
                    ("two_weeks", "Inom två veckor"),
                    ("asap", "Så snart som möjligt"),
                    ("critical", "Akut - något är trasigt"),
                ],
                max_length=10,
                verbose_name="Brådska",
            ),
        ),
    ]
