# Generated by Django 6.0.5 on 2026-09-20 18:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_kundens_uppgifter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogDigest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("period_label", models.CharField(max_length=60)),
                ("body", models.TextField()),
                ("sent_to", models.CharField(max_length=500)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_digests",
                        to="projects.customer",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Loggsammanställning",
                "verbose_name_plural": "Loggsammanställningar",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date",
                    models.DateField(default=django.utils.timezone.localdate, verbose_name="Datum"),
                ),
                ("text", models.TextField(max_length=1000, verbose_name="Text")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_entries",
                        to="projects.customer",
                    ),
                ),
                (
                    "digest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="projects.logdigest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loggpost",
                "verbose_name_plural": "Loggposter",
                "ordering": ["-date", "-id"],
            },
        ),
    ]
