# Generated by Django 6.0.5 on 2026-09-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_kundlogg"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
