# Generated by Django 6.0.5 on 2026-10-02 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_status_i_stallet_for_kolumner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="column",
            name="unique_column_title_per_project",
        ),
        migrations.RemoveIndex(
            model_name="issue",
            name="projects_is_project_f6691f_idx",
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["status", "position"], name="projects_is_status_69e324_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["project", "status"], name="projects_is_project_638a65_idx"),
        ),
        migrations.RemoveField(
            model_name="issue",
            name="column",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="started_at",
        ),
        migrations.DeleteModel(
            name="Column",
        ),
    ]
