# Generated by Django 6.0.5 on 2026-10-10 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_bort_med_kolumnerna"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("last_seen_at", models.DateTimeField(verbose_name="Aktiv senast")),
                (
                    "last_area",
                    models.CharField(
                        choices=[("portal", "Kundportalen"), ("flamingo", "Flamingo")],
                        max_length=20,
                        verbose_name="Var",
                    ),
                ),
                (
                    "last_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="projects.customer",
                        verbose_name="För kund",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_activity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kontaktaktivitet",
                "verbose_name_plural": "Kontaktaktiviteter",
            },
        ),
    ]
