# Generated by Django 6.0.5 on 2026-09-21 17:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import apps.cloud.models
import apps.projects.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0007_kundlogg"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwsAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=80, verbose_name="Namn")),
                (
                    "account_id",
                    models.CharField(
                        max_length=12,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{12}$", "Konto-ID är tolv siffror."
                            )
                        ],
                        verbose_name="Konto-ID",
                    ),
                ),
                (
                    "role_name",
                    models.CharField(default="ADXReadOnly", max_length=64, verbose_name="Roll"),
                ),
                (
                    "external_id",
                    models.CharField(
                        default=apps.cloud.models.new_external_id, editable=False, max_length=64
                    ),
                ),
                (
                    "show_invoices",
                    models.BooleanField(
                        default=True, verbose_name="Kunden ser fakturorna i portalen"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_ok_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aws_accounts",
                        to="projects.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "AWS-konto",
                "verbose_name_plural": "AWS-konton",
                "ordering": ["customer__name", "label", "account_id"],
            },
        ),
        migrations.CreateModel(
            name="AwsInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("invoice_id", models.CharField(max_length=64)),
                ("invoice_type", models.CharField(blank=True, max_length=20)),
                ("entity", models.CharField(blank=True, max_length=120, verbose_name="Utfärdare")),
                ("period_year", models.PositiveSmallIntegerField()),
                ("period_month", models.PositiveSmallIntegerField()),
                ("issued_on", models.DateField(blank=True, null=True)),
                ("due_on", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "total",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "tax",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        storage=apps.projects.models.private_storage,
                        upload_to=apps.cloud.models.invoice_pdf_path,
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="cloud.awsaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "AWS-faktura",
                "verbose_name_plural": "AWS-fakturor",
                "ordering": ["-period_year", "-period_month", "-issued_on", "invoice_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "invoice_id"), name="unik_faktura_per_konto"
                    )
                ],
            },
        ),
    ]
