# Generated by Django 6.0.5 on 2026-09-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloud", "0001_aws_konton"),
    ]

    operations = [
        migrations.AddField(
            model_name="awsinvoice",
            name="credits",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="awsinvoice",
            name="subtotal",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
