# Generated by Django 6.0.5 on 2026-06-05 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("website", "0003_sitesettings_footer_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True, verbose_name="Namn")),
                ("slug", models.SlugField(blank=True, max_length=90, unique=True)),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="Rich text (fet, kursiv, länkar).",
                        verbose_name="Intro för målgruppssida",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Sortering")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.mediafile",
                        verbose_name="Bild",
                    ),
                ),
            ],
            options={
                "verbose_name": "Målgrupp",
                "verbose_name_plural": "Målgrupper",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Namn")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=200, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Vanlig text. Används som meta-beskrivning.",
                        max_length=200,
                        verbose_name="Kort beskrivning",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Rich text (fet, kursiv, länkar) för kategorisidan.",
                        verbose_name="Brödtext",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sortering")),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.mediafile",
                        verbose_name="Bild",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tjänstekategori",
                "verbose_name_plural": "Tjänstekategorier",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Namn")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=200, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Vanlig text. Används som meta-beskrivning.",
                        max_length=200,
                        verbose_name="Kort beskrivning",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Rich text (fet, kursiv, länkar) för tjänstesidan.",
                        verbose_name="Brödtext",
                    ),
                ),
                (
                    "price_from",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Pris från (kr)"
                    ),
                ),
                (
                    "price_to",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Lämna tomt för 'Från X kr'.",
                        null=True,
                        verbose_name="Pris till (kr)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Visa i utvalda/populära sektioner.",
                        verbose_name="Utvald",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sortering")),
                (
                    "audiences",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Vilka målgruppssidor denna tjänst ska listas på.",
                        related_name="services",
                        to="services.audience",
                        verbose_name="Målgrupper",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.mediafile",
                        verbose_name="Bild",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services",
                        to="services.servicecategory",
                        verbose_name="Kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tjänst",
                "verbose_name_plural": "Tjänster",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Rubrik")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Kort beskrivning av steget (vanlig text).",
                        max_length=300,
                        verbose_name="Beskrivning",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sortering")),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="services.service",
                        verbose_name="Tjänst",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tjänststeg",
                "verbose_name_plural": "Tjänststeg",
                "ordering": ["order", "id"],
            },
        ),
    ]
