# Generated by Django 6.0.5 on 2026-06-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_emergency",
            field=models.BooleanField(
                default=False,
                help_text="Markera tjänster som erbjuds som akut utryckning/jour.",
                verbose_name="Akut/jour",
            ),
        ),
    ]
