# Generated by Django 6.0.5 on 2026-06-06 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0001_initial"),
        ("services", "0002_service_is_emergency"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="faq_section",
            field=models.ForeignKey(
                blank=True,
                help_text="Valfri FAQ som visas på tjänstesidan.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="faq.faqsection",
                verbose_name="FAQ-sektion",
            ),
        ),
    ]
