# Generated by Django 6.0.5 on 2026-06-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_service_faq_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="audience",
            name="price_note",
            field=models.CharField(
                blank=True,
                help_text="T.ex. 'Alla priser inkl. moms.' Visas under prislistan.",
                max_length=200,
                verbose_name="Prisnotis",
            ),
        ),
        migrations.AddField(
            model_name="audience",
            name="rot_applies",
            field=models.BooleanField(
                default=False,
                help_text="Visa pris efter ROT-avdrag i prislistan för denna målgrupp.",
                verbose_name="ROT-avdrag gäller",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="is_rot_eligible",
            field=models.BooleanField(
                default=False,
                help_text="Markera om tjänsten ger rätt till ROT-avdrag (gäller arbetskostnad).",
                verbose_name="ROT-berättigad",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="labor_price_from",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Arbetskostnad från (kr)"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="labor_price_to",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Arbetskostnad till (kr)"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="material_price_from",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Materialkostnad från (kr)"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="material_price_to",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Materialkostnad till (kr)"
            ),
        ),
    ]
