# Generated by Django 6.0.5 on 2026-06-12 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0004_audience_price_note_audience_rot_applies_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="price_from",
        ),
        migrations.RemoveField(
            model_name="service",
            name="price_to",
        ),
    ]
