# Generated by Django 6.0.5 on 2026-06-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_remove_service_price_from_remove_service_price_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="is_rot_eligible",
            field=models.BooleanField(
                default=True,
                help_text="Markera om tjänsten ger rätt till ROT-avdrag (gäller arbetskostnad).",
                verbose_name="ROT-berättigad",
            ),
        ),
    ]
