# Generated by Django 6.0.5 on 2026-06-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0006_alter_service_is_rot_eligible"),
    ]

    operations = [
        migrations.AddField(
            model_name="audience",
            name="prices_include_vat",
            field=models.BooleanField(
                default=True,
                help_text="På: priser visas inkl. moms (privatpersoner/BRF). Av: priser visas exkl. moms (företag).",
                verbose_name="Visa priser inkl. moms",
            ),
        ),
    ]
