# Generated by Django 6.0.5 on 2026-08-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0007_audience_prices_include_vat"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="gradient_color",
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
