# Generated by Django 6.0.5 on 2026-08-28 05:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0008_service_gradient_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audience",
            name="price_note",
        ),
        migrations.RemoveField(
            model_name="audience",
            name="prices_include_vat",
        ),
        migrations.RemoveField(
            model_name="audience",
            name="rot_applies",
        ),
        migrations.RemoveField(
            model_name="service",
            name="is_emergency",
        ),
        migrations.RemoveField(
            model_name="service",
            name="is_rot_eligible",
        ),
        migrations.RemoveField(
            model_name="service",
            name="labor_price_from",
        ),
        migrations.RemoveField(
            model_name="service",
            name="labor_price_to",
        ),
        migrations.RemoveField(
            model_name="service",
            name="material_price_from",
        ),
        migrations.RemoveField(
            model_name="service",
            name="material_price_to",
        ),
    ]
