# Generated by Django 6.0.5 on 2026-06-11 09:31

import django.db.models.deletion
from django.db import migrations, models

import apps.inquiries.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        default=apps.inquiries.models._generate_reference,
                        editable=False,
                        max_length=12,
                        unique=True,
                        verbose_name="Referensnummer",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Ny"),
                            ("in_progress", "Under hantering"),
                            ("quoted", "Offert skickad"),
                            ("closed", "Avslutad"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Läst")),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("private", "Privatperson"),
                            ("company", "Företag / Fastighet"),
                            ("brf", "BRF Bostadsrättsförening"),
                        ],
                        max_length=10,
                        verbose_name="Kundtyp",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Företagsnamn / Föreningsnamn"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Namn")),
                ("email", models.EmailField(max_length=254, verbose_name="E-post")),
                ("phone", models.CharField(max_length=50, verbose_name="Telefon")),
                ("street_address", models.CharField(max_length=255, verbose_name="Gatuadress")),
                ("postal_code", models.CharField(max_length=10, verbose_name="Postnummer")),
                ("city", models.CharField(max_length=100, verbose_name="Ort")),
                ("description", models.TextField(verbose_name="Beskrivning av ärende")),
            ],
            options={
                "verbose_name": "Förfrågan",
                "verbose_name_plural": "Förfrågningar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InquiryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.ImageField(upload_to="inquiries/%Y/%m/", verbose_name="Bild")),
                ("original_filename", models.CharField(max_length=255, verbose_name="Filnamn")),
                ("file_size", models.PositiveIntegerField(default=0, verbose_name="Filstorlek")),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="inquiries.inquiry",
                        verbose_name="Förfrågan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bifogad bild",
                "verbose_name_plural": "Bifogade bilder",
            },
        ),
    ]
