# Generated by Django 6.0.5 on 2026-06-11 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
        ("inquiries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="analytics_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inquiries",
                to="analytics.session",
                verbose_name="Analyssession",
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="traffic_referrer",
            field=models.URLField(blank=True, max_length=1000, verbose_name="Referrer"),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="traffic_source",
            field=models.CharField(
                blank=True,
                help_text="Snapshot: var besökaren kom ifrån (Google, Facebook, …).",
                max_length=20,
                verbose_name="Trafikkälla",
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="traffic_source_detail",
            field=models.CharField(blank=True, max_length=100, verbose_name="Trafikkälla (detalj)"),
        ),
    ]
