# Generated by Django 6.0.5 on 2026-08-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0002_inquiry_analytics_session_inquiry_traffic_referrer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="E-post")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source_path", models.CharField(blank=True, max_length=200, verbose_name="Sida")),
            ],
            options={
                "verbose_name": "Nyhetsbrevsprenumerant",
                "verbose_name_plural": "Nyhetsbrevsprenumeranter",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="inquiry",
            name="budget",
            field=models.CharField(
                blank=True,
                choices=[
                    ("under_25", "Under 25 000 kr"),
                    ("25_100", "25 000 – 100 000 kr"),
                    ("100_250", "100 000 – 250 000 kr"),
                    ("over_250", "Över 250 000 kr"),
                    ("monthly", "Löpande månadsbudget"),
                    ("unknown", "Vet inte än"),
                ],
                max_length=20,
                verbose_name="Ungefärlig budget",
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="timeline",
            field=models.CharField(
                blank=True,
                choices=[
                    ("asap", "Så snart som möjligt"),
                    ("quarter", "Inom 1–3 månader"),
                    ("later", "Senare i år"),
                    ("exploring", "Utforskar bara"),
                ],
                max_length=20,
                verbose_name="Önskad tidplan",
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="topic",
            field=models.CharField(blank=True, max_length=100, verbose_name="Gäller"),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ort"),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="customer_type",
            field=models.CharField(
                choices=[
                    ("company", "Företag"),
                    ("org", "Organisation / Förening"),
                    ("private", "Privatperson"),
                ],
                default="company",
                max_length=10,
                verbose_name="Kundtyp",
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, verbose_name="Postnummer"),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="street_address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Gatuadress"),
        ),
    ]
