# Generated by Django 6.0.5 on 2026-08-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_newslettersignup_inquiry_budget_inquiry_timeline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='budget',
            field=models.CharField(blank=True, choices=[('under_25', 'Under 25 000 kr'), ('25_100', '25 000 - 100 000 kr'), ('100_250', '100 000 - 250 000 kr'), ('over_250', 'Över 250 000 kr'), ('monthly', 'Löpande månadsbudget'), ('unknown', 'Vet inte än')], max_length=20, verbose_name='Ungefärlig budget'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='timeline',
            field=models.CharField(blank=True, choices=[('asap', 'Så snart som möjligt'), ('quarter', 'Inom 1-3 månader'), ('later', 'Senare i år'), ('exploring', 'Utforskar bara')], max_length=20, verbose_name='Önskad tidplan'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='traffic_source',
            field=models.CharField(blank=True, help_text='Snapshot: var besökaren kom ifrån (Google, Facebook, ...).', max_length=20, verbose_name='Trafikkälla'),
        ),
    ]
