# Generated by Django 6.0.5 on 2026-06-06 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=200, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Valfri intro som visas på FAQ-sidan.",
                        verbose_name="Beskrivning",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="SEO-beskrivning (max 160 tecken).",
                        max_length=160,
                        verbose_name="Metabeskrivning",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sortering")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ-sektion",
                "verbose_name_plural": "FAQ-sektioner",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="FAQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question", models.CharField(max_length=500, verbose_name="Fråga")),
                (
                    "answer",
                    models.TextField(
                        help_text="Grundläggande HTML (fet, kursiv, listor, länkar) tillåtet.",
                        verbose_name="Svar",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sortering")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="faq.faqsection",
                        verbose_name="Sektion",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ-fråga",
                "verbose_name_plural": "FAQ-frågor",
                "ordering": ["order", "id"],
            },
        ),
    ]
