# Generated by Django 6.0.5 on 2026-10-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faqsection",
            name="design",
            field=models.CharField(
                blank=True,
                choices=[("", "ADX"), ("flamingo", "ADX Flamingo")],
                default="",
                help_text="ADX Flamingo: visas bara på Flamingo-sidor, aldrig publikt.",
                max_length=20,
                verbose_name="Design",
            ),
        ),
    ]
