# Generated by Django 6.0.5 on 2026-08-07 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("reversion", "0002_add_index_on_version_for_content_type_and_db"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("session_key", models.CharField(blank=True, db_index=True, max_length=128)),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="Rubrik")),
                ("prompt", models.TextField(blank=True, verbose_name="Instruktion")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Väntar på granskning"),
                            ("applied", "Genomfört"),
                            ("discarded", "Förkastat"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("tool_log", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI-jobb",
                "verbose_name_plural": "AI-jobb",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssistantToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(default="AI-koppling", max_length=100, verbose_name="Namn"),
                ),
                ("key_hash", models.CharField(editable=False, max_length=64, unique=True)),
                ("key_hint", models.CharField(editable=False, max_length=12)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI-nyckel",
                "verbose_name_plural": "AI-nycklar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DraftChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("operation", models.CharField(max_length=60)),
                (
                    "risk",
                    models.CharField(
                        choices=[
                            ("read", "Läsning"),
                            ("text", "Textändring"),
                            ("business", "Affärsdata"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "summary",
                    models.CharField(blank=True, max_length=300, verbose_name="Sammanfattning"),
                ),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                ("payload", models.JSONField()),
                ("before", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Väntar"),
                            ("rejected", "Avslagen"),
                            ("applied", "Genomförd"),
                            ("failed", "Misslyckades"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "depends_on",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependants",
                        to="assistant.draftchange",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="assistant.aijob",
                    ),
                ),
                (
                    "target_ct",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utkast",
                "verbose_name_plural": "Utkast",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="RevisionMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manuell ändring"),
                            ("ai", "AI-förslag"),
                            ("import", "Import"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("prompt", models.TextField(blank=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisions",
                        to="assistant.aijob",
                    ),
                ),
                (
                    "revision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta",
                        to="reversion.revision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revisionsmetadata",
                "verbose_name_plural": "Revisionsmetadata",
            },
        ),
    ]
