# Generated by Django 6.0.5 on 2026-08-07 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("client_id", models.CharField(editable=False, max_length=64, unique=True)),
                ("client_secret_hash", models.CharField(blank=True, editable=False, max_length=64)),
                ("client_name", models.CharField(blank=True, max_length=200)),
                ("redirect_uris", models.JSONField(default=list)),
                ("grant_types", models.JSONField(default=list)),
                ("response_types", models.JSONField(default=list)),
                (
                    "token_endpoint_auth_method",
                    models.CharField(default="client_secret_post", max_length=40),
                ),
                ("scope", models.CharField(default="redaktor", max_length=200)),
                ("client_uri", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "OAuth-klient",
                "verbose_name_plural": "OAuth-klienter",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuthorizationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code_hash", models.CharField(editable=False, max_length=64, unique=True)),
                ("redirect_uri", models.CharField(max_length=500)),
                ("redirect_uri_provided_explicitly", models.BooleanField(default=True)),
                ("code_challenge", models.CharField(max_length=200)),
                ("scopes", models.JSONField(default=list)),
                ("resource", models.CharField(blank=True, max_length=500)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes",
                        to="assistant.oauthclient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auktoriseringskod",
                "verbose_name_plural": "Auktoriseringskoder",
            },
        ),
        migrations.CreateModel(
            name="OAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("access", "Access-token"), ("refresh", "Refresh-token")],
                        max_length=8,
                    ),
                ),
                ("token_hash", models.CharField(editable=False, max_length=64, unique=True)),
                ("scopes", models.JSONField(default=list)),
                ("resource", models.CharField(blank=True, max_length=500)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="assistant.oauthclient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth-token",
                "verbose_name_plural": "OAuth-tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["kind", "expires_at"], name="assistant_o_kind_6f088a_idx")
                ],
            },
        ),
    ]
