# Generated by Django 6.0.5 on 2026-08-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0002_oauthclient_authorizationcode_oauthtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oauthclient",
            name="client_secret_hash",
        ),
        migrations.AddField(
            model_name="oauthclient",
            name="client_secret_encrypted",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
