# Generated by Django 6.0.5 on 2026-08-21 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0003_remove_oauthclient_client_secret_hash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "Kund"), ("assistant", "Assistent")], max_length=10
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Arbetar"),
                            ("done", "Klart"),
                            ("failed", "Misslyckades"),
                        ],
                        default="done",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("transcript", models.JSONField(blank=True, default=list)),
                ("steps", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="assistant.aijob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chattmeddelande",
                "verbose_name_plural": "Chattmeddelanden",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="AICall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("model", models.CharField(max_length=60)),
                ("tokens_in", models.PositiveIntegerField(default=0)),
                ("tokens_out", models.PositiveIntegerField(default=0)),
                ("tokens_cached", models.PositiveIntegerField(default=0)),
                ("cost_micros", models.PositiveIntegerField(default=0, help_text="Mikrodollar")),
                ("stop_reason", models.CharField(blank=True, max_length=40)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("ok", models.BooleanField(default=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="assistant.aijob",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI-anrop",
                "verbose_name_plural": "AI-anrop",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="assistant_a_created_c33401_idx")
                ],
            },
        ),
    ]
