# Generated by Django 6.0.5 on 2026-09-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0004_chatmessage_aicall"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftchange",
            name="risk",
            field=models.CharField(
                choices=[
                    ("read", "Läsning"),
                    ("text", "Textändring"),
                    ("business", "Affärsdata"),
                    ("action", "Direkt"),
                ],
                max_length=10,
            ),
        ),
    ]
