# Generated by Django 6.0.5 on 2026-10-03 20:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.sms.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0011_bort_med_kolumnerna"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False, verbose_name="Aktiverat")),
                ("enabled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sender_name",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[apps.sms.models.validate_sender],
                        verbose_name="Avsändare",
                    ),
                ),
                (
                    "markup_ore_per_part",
                    models.PositiveIntegerField(default=5, verbose_name="Påslag per sms-del (öre)"),
                ),
                (
                    "yearly_fee_kr",
                    models.PositiveIntegerField(default=999, verbose_name="Årsavgift (kr)"),
                ),
                (
                    "monthly_cap_kr",
                    models.PositiveIntegerField(
                        default=500, verbose_name="Kostnadstak per månad (kr)"
                    ),
                ),
                (
                    "allowed_countries",
                    models.JSONField(
                        default=apps.sms.models.default_countries, verbose_name="Tillåtna länder"
                    ),
                ),
                (
                    "service_year_start",
                    models.DateField(blank=True, null=True, verbose_name="Tjänsteåret börjar"),
                ),
                ("cap_alerted_period", models.DateField(blank=True, editable=False, null=True)),
                (
                    "provider_alerted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_account",
                        to="projects.customer",
                    ),
                ),
                (
                    "enabled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS-konto",
                "verbose_name_plural": "SMS-konton",
                "ordering": ["customer__name"],
            },
        ),
        migrations.CreateModel(
            name="SmsApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Namn")),
                ("prefix", models.CharField(editable=False, max_length=16)),
                ("secret_hash", models.CharField(editable=False, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="sms.smsaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS-nyckel",
                "verbose_name_plural": "SMS-nycklar",
                "ordering": ["revoked_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("period", models.DateField()),
                ("sms_count", models.PositiveIntegerField(default=0)),
                ("parts", models.PositiveIntegerField(default=0)),
                ("provider_cost", models.BigIntegerField(default=0)),
                ("markup", models.BigIntegerField(default=0)),
                ("fee", models.BigIntegerField(default=0)),
                ("total", models.BigIntegerField(default=0)),
                ("lines", models.JSONField(default=list)),
                ("markup_ore_per_part", models.PositiveIntegerField(default=0)),
                ("yearly_fee_kr", models.PositiveIntegerField(default=0)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="statements",
                        to="sms.smsaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Månadsunderlag",
                "verbose_name_plural": "Månadsunderlag",
                "ordering": ["-period", "account__customer__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "period"), name="sms_statement_unique_period"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SmsMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=64)),
                ("to", models.CharField(max_length=32, verbose_name="Till")),
                ("country", models.CharField(blank=True, max_length=2, verbose_name="Land")),
                ("sender", models.CharField(blank=True, max_length=11, verbose_name="Från")),
                ("body", models.TextField(verbose_name="Text")),
                ("parts", models.PositiveSmallIntegerField(default=0, verbose_name="Delar")),
                (
                    "encoding",
                    models.CharField(
                        choices=[("gsm7", "GSM-7"), ("ucs2", "UCS-2")], default="gsm7", max_length=4
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Skickas"),
                            ("sent", "Skickat"),
                            ("delivered", "Levererat"),
                            ("failed", "Misslyckades"),
                            ("rejected", "Stoppat"),
                            ("blocked_cap", "Taket nått"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=32)),
                ("error", models.CharField(blank=True, max_length=300)),
                ("provider_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("estimated_cost", models.IntegerField(default=0)),
                ("provider_cost", models.IntegerField(default=0)),
                ("markup", models.IntegerField(default=0)),
                ("customer_price", models.IntegerField(default=0)),
                ("test_mode", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="sms.smsaccount",
                    ),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="sms.smsapikey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sms",
                "verbose_name_plural": "Sms",
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(fields=["account", "created_at"], name="sms_msg_account_created"),
                    models.Index(fields=["api_key", "created_at"], name="sms_msg_key_created"),
                    models.Index(fields=["country", "sent_at"], name="sms_msg_country_sent"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            models.Q(("reference", ""), _negated=True),
                            models.Q(("status__in", ["rejected", "blocked_cap"]), _negated=True),
                            models.Q(("error_code", "provider_error"), _negated=True),
                        ),
                        fields=("account", "reference"),
                        name="sms_msg_unique_reference",
                    )
                ],
            },
        ),
    ]
