# Generated by Django 6.0.5 on 2026-10-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sms", "0002_konto_och_avstamning"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsaccount",
            name="customer_manages_api",
            field=models.BooleanField(
                default=False, verbose_name="Kunden sköter nycklar, tak och dokumentation själv"
            ),
        ),
    ]
