# Generated by Django 6.0.5 on 2026-10-06 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sms", "0003_kunden_skoter_api"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="smsaccount",
            name="customer_sets_sender",
            field=models.BooleanField(default=False, verbose_name="Kunden får välja avsändarnamn"),
        ),
        migrations.AddField(
            model_name="smsaccount",
            name="sender_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="smsaccount",
            name="sender_changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
