# Generated by Django 6.0.5 on 2026-10-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sms", "0004_kunden_valjer_avsandare"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsaccount",
            name="extra_senders",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Extra godkända avsändare"
            ),
        ),
        migrations.AlterField(
            model_name="smsaccount",
            name="customer_sets_sender",
            field=models.BooleanField(
                default=False, verbose_name="Kunden får välja avsändare via API:et"
            ),
        ),
    ]
