# Generated by Django 6.0.5 on 2026-06-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={"ordering": ["location", "order", "id"]},
        ),
        migrations.RemoveConstraint(
            model_name="menu",
            name="unique_menu_location",
        ),
        migrations.AddField(
            model_name="menu",
            name="heading",
            field=models.CharField(
                blank=True,
                help_text="Public column heading (footer). Leave blank for no heading.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Ordering among menus in the same location (footer columns)."
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="name",
            field=models.CharField(
                help_text="Internal name (admin only, not shown on the site).", max_length=100
            ),
        ),
    ]
