# Generated by Django 6.0.5 on 2026-06-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_alter_menu_options_remove_menu_unique_menu_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="footer_about",
            field=models.TextField(blank=True),
        ),
    ]
