# Generated by Django 6.0.5 on 2026-06-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_sitesettings_footer_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="show_logo_in_footer",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_logo_in_header",
            field=models.BooleanField(default=True),
        ),
    ]
