# Generated by Django 6.0.5 on 2026-06-06 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_sitesettings_show_logo_in_footer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="footer_component_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="website.blockpage",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ga_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ga_tracking_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="reco_widget_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_reco_widget",
            field=models.BooleanField(default=False),
        ),
    ]
