# Generated by Django 6.0.5 on 2026-06-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_sitesettings_footer_component_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="is_button",
            field=models.BooleanField(
                default=False, help_text="Render as a call-to-action button (header menu only)."
            ),
        ),
    ]
