# Generated by Django 6.0.5 on 2026-06-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_menuitem_is_button"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="rot_percentage",
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
