# Generated by Django 6.0.5 on 2026-06-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_sitesettings_rot_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="vat_rate",
            field=models.PositiveSmallIntegerField(default=25),
        ),
    ]
