# Generated by Django 6.0.5 on 2026-06-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_sitesettings_vat_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="is_optimized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="original_file",
            field=models.FileField(
                blank=True,
                help_text="Original file before optimization. Empty until first optimize.",
                upload_to="media/originals/",
            ),
        ),
    ]
