# Generated by Django 6.0.5 on 2026-08-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_mediafile_is_optimized_mediafile_original_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="ai_style_guide",
            field=models.TextField(
                blank=True,
                help_text="Tonläge och skrivregler som AI-assistenten följer. T.ex. tilltal, längd, ord att undvika.",
                verbose_name="Skrivguide för AI",
            ),
        ),
    ]
