# Generated by Django 6.0.5 on 2026-08-26 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_sitesettings_ai_style_guide"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="focal_x",
            field=models.PositiveSmallIntegerField(
                default=50, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="focal_y",
            field=models.PositiveSmallIntegerField(
                default=50, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
    ]
