# Generated by Django 6.0.5 on 2026-08-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0011_mediafile_focal_x_mediafile_focal_y"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockpage",
            name="gradient_color",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_gradient_color",
            field=models.CharField(blank=True, default="#f7fcff", max_length=7),
        ),
    ]
