# Generated by Django 6.0.5 on 2026-08-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0012_blockpage_gradient_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("hero", "Hero"),
                    ("chips", "Nyckeltal (chips)"),
                    ("marquee", "Rullande band"),
                    ("svc_list", "Tjänstelista"),
                    ("case", "Case"),
                    ("steps", "Steg"),
                    ("quotes", "Citat"),
                    ("why", "Varför vi"),
                    ("bar", "CTA-rad"),
                    ("split", "Bild + text"),
                    ("folio", "Portfolio-kort"),
                    ("plans", "Paket"),
                    ("compare", "Jämförelsetabell"),
                    ("team", "Team"),
                    ("faq", "FAQ"),
                    ("prose", "SEO-text"),
                    ("related", "Relaterade länkar"),
                    ("contact_cards", "Kontaktkort"),
                    ("inquiry_form", "Förfrågningsformulär"),
                    ("newsletter", "Nyhetsbrev"),
                    ("spacer", "Mellanrum"),
                ],
                max_length=20,
            ),
        ),
    ]
