# Generated by Django 6.0.5 on 2026-08-28 05:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0013_alter_block_block_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="reco_widget_url",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="rot_percentage",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="show_reco_widget",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="vat_rate",
        ),
    ]
