# Generated by Django 6.0.5 on 2026-10-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0017_fler_svarstidsloften"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockpage",
            name="design",
            field=models.CharField(
                blank=True,
                choices=[("", "ADX"), ("flamingo", "ADX Flamingo")],
                default="",
                max_length=20,
                verbose_name="Design",
            ),
        ),
    ]
