# Generated by Django 6.0.5 on 2026-06-11 14:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, editable=False, unique=True, verbose_name="Besökar-ID"
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Först sedd"
                    ),
                ),
                (
                    "first_referrer",
                    models.URLField(blank=True, max_length=1000, verbose_name="Första referrer"),
                ),
                (
                    "first_source",
                    models.CharField(
                        choices=[
                            ("direct", "Direkt"),
                            ("organic", "Sökmotor"),
                            ("social", "Sociala medier"),
                            ("referral", "Hänvisning"),
                            ("email", "E-post"),
                            ("paid", "Annons"),
                            ("internal", "Intern"),
                        ],
                        default="direct",
                        max_length=20,
                        verbose_name="Första källa",
                    ),
                ),
                (
                    "first_source_detail",
                    models.CharField(
                        blank=True,
                        help_text="T.ex. google, facebook, newsletter.",
                        max_length=100,
                        verbose_name="Första källa (detalj)",
                    ),
                ),
                (
                    "first_landing_page",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Första landningssida"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Senast sedd"
                    ),
                ),
                (
                    "session_count",
                    models.PositiveIntegerField(default=0, verbose_name="Antal besök"),
                ),
            ],
            options={
                "verbose_name": "Besökare",
                "verbose_name_plural": "Besökare",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, editable=False, unique=True, verbose_name="Sessions-ID"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Startade"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Senaste aktivitet"
                    ),
                ),
                (
                    "pageview_count",
                    models.PositiveIntegerField(default=0, verbose_name="Antal sidvisningar"),
                ),
                ("referrer", models.URLField(blank=True, max_length=1000, verbose_name="Referrer")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("direct", "Direkt"),
                            ("organic", "Sökmotor"),
                            ("social", "Sociala medier"),
                            ("referral", "Hänvisning"),
                            ("email", "E-post"),
                            ("paid", "Annons"),
                            ("internal", "Intern"),
                        ],
                        default="direct",
                        max_length=20,
                        verbose_name="Källa",
                    ),
                ),
                (
                    "source_detail",
                    models.CharField(blank=True, max_length=100, verbose_name="Källa (detalj)"),
                ),
                (
                    "landing_page",
                    models.CharField(blank=True, max_length=500, verbose_name="Landningssida"),
                ),
                (
                    "utm_source",
                    models.CharField(blank=True, max_length=100, verbose_name="UTM source"),
                ),
                (
                    "utm_medium",
                    models.CharField(blank=True, max_length=100, verbose_name="UTM medium"),
                ),
                (
                    "utm_campaign",
                    models.CharField(blank=True, max_length=100, verbose_name="UTM campaign"),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "Dator"),
                            ("mobile", "Mobil"),
                            ("tablet", "Surfplatta"),
                            ("bot", "Bot"),
                            ("unknown", "Okänd"),
                        ],
                        default="unknown",
                        max_length=10,
                        verbose_name="Enhetstyp",
                    ),
                ),
                ("os", models.CharField(blank=True, max_length=60, verbose_name="Operativsystem")),
                ("browser", models.CharField(blank=True, max_length=60, verbose_name="Webbläsare")),
                (
                    "screen_resolution",
                    models.CharField(blank=True, max_length=20, verbose_name="Skärmupplösning"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User agent")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP (anonymiserad)"
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=2, verbose_name="Land")),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="analytics.visitor",
                        verbose_name="Besökare",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessioner",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.CharField(max_length=500, verbose_name="Sökväg")),
                ("title", models.CharField(blank=True, max_length=255, verbose_name="Sidtitel")),
                (
                    "viewed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Tidpunkt"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pageviews",
                        to="analytics.session",
                        verbose_name="Session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sidvisning",
                "verbose_name_plural": "Sidvisningar",
                "ordering": ["viewed_at"],
                "indexes": [
                    models.Index(fields=["path"], name="analytics_p_path_3382b5_idx"),
                    models.Index(fields=["viewed_at"], name="analytics_p_viewed__6302cc_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("tel_click", "Telefonklick"),
                            ("email_click", "E-postklick"),
                            ("booking", "Förfrågan/bokning"),
                            ("outbound", "Extern länk"),
                            ("other", "Övrigt"),
                        ],
                        max_length=20,
                        verbose_name="Händelsetyp",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=255, verbose_name="Etikett")),
                ("path", models.CharField(blank=True, max_length=500, verbose_name="Sökväg")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Tidpunkt"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="analytics.session",
                        verbose_name="Session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Händelse",
                "verbose_name_plural": "Händelser",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["event_type"], name="analytics_e_event_t_acfd0a_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["-started_at"], name="analytics_s_started_783082_idx"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["source"], name="analytics_s_source_3ead92_idx"),
        ),
    ]
