# Generated by Django 6.0.5 on 2026-08-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="placement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("header", "Sidhuvud"),
                    ("mobile_nav", "Mobilmeny"),
                    ("hero", "Hero-sektion"),
                    ("cta", "CTA-sektion"),
                    ("quote_cta", "Offert-CTA"),
                    ("sticky", "Fast knapp"),
                    ("footer", "Sidfot"),
                    ("content", "I löpande text"),
                    ("other", "Övrigt"),
                ],
                help_text="Var på sidan interaktionen skedde, t.ex. sidhuvud eller sidfot.",
                max_length=20,
                verbose_name="Placering",
            ),
        ),
        migrations.AddField(
            model_name="pageview",
            name="engaged_seconds",
            field=models.PositiveIntegerField(default=0, verbose_name="Engagerad tid (s)"),
        ),
        migrations.AddField(
            model_name="session",
            name="engaged_seconds",
            field=models.PositiveIntegerField(default=0, verbose_name="Engagerad tid (s)"),
        ),
        migrations.AddField(
            model_name="session",
            name="utm_content",
            field=models.CharField(blank=True, max_length=100, verbose_name="UTM content"),
        ),
        migrations.AddField(
            model_name="session",
            name="utm_term",
            field=models.CharField(blank=True, max_length=100, verbose_name="UTM term"),
        ),
        migrations.AddField(
            model_name="session",
            name="viewport_height",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Vyporthöjd"),
        ),
        migrations.AddField(
            model_name="session",
            name="viewport_width",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Vyportbredd"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("tel_click", "Telefonklick"),
                    ("email_click", "E-postklick"),
                    ("booking", "Förfrågan/bokning"),
                    ("outbound", "Extern länk"),
                    ("form_error", "Formulärfel"),
                    ("form_abandon", "Formuläravhopp"),
                    ("other", "Övrigt"),
                ],
                max_length=20,
                verbose_name="Händelsetyp",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["-created_at"], name="analytics_e_created_659b3f_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_type", "-created_at"], name="analytics_e_event_t_a1a31c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["session", "path", "-viewed_at"], name="analytics_p_session_997450_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["session", "-viewed_at"], name="analytics_p_session_e88af7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitor",
            index=models.Index(fields=["-last_seen"], name="analytics_v_last_se_7d0bd0_idx"),
        ),
        migrations.AddIndex(
            model_name="visitor",
            index=models.Index(fields=["first_seen"], name="analytics_v_first_s_f954e7_idx"),
        ),
        migrations.AddIndex(
            model_name="visitor",
            index=models.Index(fields=["first_source"], name="analytics_v_first_s_6ac80a_idx"),
        ),
    ]
