# Generated by Django 6.0.5 on 2026-09-20 18:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0007_kundlogg"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoredDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="t.ex. nordanbygg.se",
                        max_length=253,
                        unique=True,
                        verbose_name="Domän",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False, verbose_name="Primär")),
                ("is_active", models.BooleanField(default=True, verbose_name="Övervakas")),
                ("status_url", models.URLField(blank=True, verbose_name="Statusendpoint")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="projects.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Övervakad domän",
                "verbose_name_plural": "Övervakade domäner",
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=300)),
                ("alerted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="monitor.monitoreddomain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avbrott",
                "verbose_name_plural": "Avbrott",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="MonitorSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "show_uptime",
                    models.BooleanField(default=True, verbose_name="Drifttid (online-status)"),
                ),
                ("show_response", models.BooleanField(default=True, verbose_name="Svarstid")),
                ("show_ssl", models.BooleanField(default=True, verbose_name="HTTPS-certifikat")),
                (
                    "show_domain",
                    models.BooleanField(default=True, verbose_name="Domän och registrar"),
                ),
                ("show_email", models.BooleanField(default=True, verbose_name="E-postens hälsa")),
                (
                    "show_performance",
                    models.BooleanField(default=True, verbose_name="Prestanda (PageSpeed)"),
                ),
                ("show_security", models.BooleanField(default=True, verbose_name="Säkerhet")),
                (
                    "show_visits",
                    models.BooleanField(
                        default=False, verbose_name="Besök (kräver statusendpoint)"
                    ),
                ),
                (
                    "show_server",
                    models.BooleanField(
                        default=False, verbose_name="Server (kräver statusendpoint)"
                    ),
                ),
                ("show_errors", models.BooleanField(default=False, verbose_name="Fel i Sentry")),
                (
                    "show_gbp",
                    models.BooleanField(default=False, verbose_name="Google Business Profile"),
                ),
                (
                    "show_search",
                    models.BooleanField(
                        default=False, verbose_name="Sökpositioner (Search Console)"
                    ),
                ),
                (
                    "show_events",
                    models.BooleanField(default=True, verbose_name="Händelser (tidslinje)"),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="Anteckning från ADX"
                    ),
                ),
                (
                    "sentry_project",
                    models.CharField(blank=True, max_length=80, verbose_name="Sentry-projekt"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitor",
                        to="projects.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Övervakningsinställning",
                "verbose_name_plural": "Övervakningsinställningar",
            },
        ),
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("uptime", "Drifttid och svarstid"),
                            ("ssl", "HTTPS-certifikat"),
                            ("domain", "Domän och registrar"),
                            ("email", "E-postens hälsa"),
                            ("performance", "Prestanda"),
                            ("security", "Säkerhet"),
                            ("snapshot", "Server (statusendpoint)"),
                            ("errors", "Fel i Sentry"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("ok", models.BooleanField(default=True)),
                ("ms", models.PositiveIntegerField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="monitor.monitoreddomain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kontroll",
                "verbose_name_plural": "Kontroller",
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["domain", "kind", "-checked_at"],
                        name="monitor_che_domain__e88bb6_idx",
                    )
                ],
            },
        ),
    ]
