# Generated by Django 6.0.5 on 2026-10-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0001_overvakning"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoreddomain",
            name="gbp_account",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Business Profile-konto"
            ),
        ),
        migrations.AddField(
            model_name="monitoreddomain",
            name="gbp_location",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Business Profile-plats"
            ),
        ),
        migrations.AddField(
            model_name="monitoreddomain",
            name="gbp_title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Business Profile-namn"
            ),
        ),
        migrations.AddField(
            model_name="monitoreddomain",
            name="search_property",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Search Console-egendom"
            ),
        ),
        migrations.AlterField(
            model_name="check",
            name="kind",
            field=models.CharField(
                choices=[
                    ("uptime", "Drifttid och svarstid"),
                    ("ssl", "HTTPS-certifikat"),
                    ("domain", "Domän och registrar"),
                    ("email", "E-postens hälsa"),
                    ("performance", "Prestanda"),
                    ("security", "Säkerhet"),
                    ("snapshot", "Server (statusendpoint)"),
                    ("errors", "Fel i Sentry"),
                    ("crux", "Riktiga besökare (Chrome UX Report)"),
                    ("search", "Google-sök (Search Console)"),
                    ("gbp", "Google Business Profile"),
                ],
                max_length=12,
            ),
        ),
    ]
