# Generated by Django 6.0.5 on 2026-08-05 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("faq", "0001_initial"),
        ("services", "0007_audience_prices_include_vat"),
        ("website", "0009_mediafile_is_optimized_mediafile_original_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, verbose_name="Namn")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=140, unique=True, verbose_name="Webbadress"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("region", "Län"),
                            ("municipality", "Kommun"),
                            ("district", "Stadsdel/Ort"),
                        ],
                        default="municipality",
                        max_length=20,
                        verbose_name="Nivå",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        blank=True,
                        help_text="Lämna tomt för 'Rörmokare i {namn}'.",
                        max_length=200,
                        verbose_name="Rubrik (H1)",
                    ),
                ),
                (
                    "intro",
                    models.CharField(
                        blank=True,
                        help_text="Kort text under rubriken. Vanlig text.",
                        max_length=300,
                        verbose_name="Underrubrik",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Rich text. Skriv något som bara stämmer för det här området - det är det som skiljer sidan från en mall.",
                        verbose_name="Lokal text",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Av döljer området och alla underområden.",
                        verbose_name="Aktiv",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sortering")),
                (
                    "meta_title",
                    models.CharField(blank=True, max_length=70, verbose_name="Sidtitel (SEO)"),
                ),
                (
                    "meta_description",
                    models.CharField(blank=True, max_length=200, verbose_name="Beskrivning (SEO)"),
                ),
                (
                    "faq_section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Visas efter områdets egna frågor.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="areas",
                        to="faq.faqsection",
                        verbose_name="Delad FAQ-sektion",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.mediafile",
                        verbose_name="Bild",
                    ),
                ),
                (
                    "neighbours",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Länkas längst ner på sidan.",
                        related_name="neighbour_of",
                        to="areas.area",
                        verbose_name="Grannområden",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Kommun för en stadsdel, län för en kommun.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="areas.area",
                        verbose_name="Överordnat område",
                    ),
                ),
            ],
            options={
                "verbose_name": "Serviceområde",
                "verbose_name_plural": "Serviceområden",
                "ordering": ["level", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AreaFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=300, verbose_name="Fråga")),
                ("answer", models.TextField(verbose_name="Svar")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sortering")),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faq_items",
                        to="areas.area",
                        verbose_name="Område",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vanlig fråga (område)",
                "verbose_name_plural": "Vanliga frågor (område)",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="AreaService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "has_own_page",
                    models.BooleanField(
                        default=False,
                        help_text="Skapar t.ex. /vvs/solna/byte-av-blandare/.",
                        verbose_name="Egen sida",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sortering")),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_services",
                        to="areas.area",
                        verbose_name="Område",
                    ),
                ),
                (
                    "audiences",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tomt = visas för alla målgrupper.",
                        related_name="area_services",
                        to="services.audience",
                        verbose_name="Målgrupper",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_links",
                        to="services.service",
                        verbose_name="Tjänst",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tjänst i område",
                "verbose_name_plural": "Tjänster i område",
                "ordering": ["order", "service__order", "service__name"],
            },
        ),
        migrations.AddField(
            model_name="area",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                related_name="areas",
                through="areas.AreaService",
                to="services.service",
                verbose_name="Tjänster",
            ),
        ),
        migrations.AddConstraint(
            model_name="areaservice",
            constraint=models.UniqueConstraint(
                fields=("area", "service"), name="unique_area_service"
            ),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(fields=["level", "is_active"], name="areas_area_level_7965a8_idx"),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(fields=["parent", "order"], name="areas_area_parent__6d8f51_idx"),
        ),
    ]
