# Generated by Django 6.0.5 on 2026-08-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("areas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="Latitud"
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="Longitud"
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="map_zoom",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Lämna tomt för standard: 8 för län, 11 för kommun, 13 för ort.",
                null=True,
                verbose_name="Zoomnivå",
            ),
        ),
    ]
