# Generated by Django 6.0.5 on 2026-08-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("areas", "0002_area_latitude_area_longitude_area_map_zoom"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="gradient_color",
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
