# Generated by Django 6.0.5 on 2026-08-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("areas", "0003_area_gradient_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="heading",
            field=models.CharField(
                blank=True,
                help_text="Lämna tomt för 'Digitalbyrå i {namn}'.",
                max_length=200,
                verbose_name="Rubrik (H1)",
            ),
        ),
        migrations.AlterField(
            model_name="areaservice",
            name="has_own_page",
            field=models.BooleanField(
                default=False,
                help_text="Används inte - kombinationssidor per tjänst och stad finns inte i ADX.",
                verbose_name="Egen sida",
            ),
        ),
    ]
